public class Sample
{
    public String one {get;set;}
    public String two {get;set;}
    public String three {get;set;}
    public String four {get;set;}
    public String five {get;set;}    
    
    public sample()
    {            
    }      
    
    public void show123()
    {
        one = 'Block one';        
        two = 'Block two';        
        three = 'Block three';        
    } 
    
    public void show45()
    {
        four = 'Block four';
        five = 'Block five';                
    }     
}